[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Default to local development API URL
  VITE_API_URL = "http://localhost:5000/api"

# Production environment settings
[context.production.environment]
  VITE_API_URL = "https://mba-fulfillment-api.onrender.com/api"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
